//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.09 at 10:10:23 AM CST 
//


package com.elong.nbopen.api.model.elong;

import com.alibaba.fastjson.annotation.JSONField;

import java.math.BigDecimal;

public class Invoice {

    /**
     * 发票类型
     * Paper-纸质发票，Electronic-电子发票
     */
    @JSONField(name = "InvoiceType")
    private String invoiceType;

    /**
     * 抬头类型
     * Personally-个人，Enterprise- 企业，Government-政府机关行政单位
     */
    @JSONField(name = "TitleType")
    private String titleType;

    /**
     * 抬头
     */
    @JSONField(name = "Title")
    private String title;

    /**
     * 纳税人识别号/统一社会信用代码
     */
    @JSONField(name = "ITIN")
    private String itin;

    /**
     * 发票内容
     * 代订房费或代订住宿费
     */
    @JSONField(name = "ItemName")
    private String itemName;

    /**
     * 金额
     */
    @JSONField(name = "Amount")
    private BigDecimal amount;

    /**
     * 是否增加发票备注
     */
    @JSONField(name = "IsNeedRelationOrder")
    private Boolean isNeedRelationOrder;

    /**
     * 收件人信息
     */
    @JSONField(name = "Recipient")
    private Recipient recipient;

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the itemName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getItemName() {
        return itemName;
    }

    /**
     * Sets the value of the itemName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setItemName(String value) {
        this.itemName = value;
    }

    /**
     * Gets the value of the amount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * Sets the value of the amount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAmount(BigDecimal value) {
        this.amount = value;
    }

    /**
     * Gets the value of the recipient property.
     * 
     * @return
     *     possible object is
     *     {@link Recipient }
     *     
     */
    public Recipient getRecipient() {
        return recipient;
    }

    /**
     * Sets the value of the recipient property.
     * 
     * @param value
     *     allowed object is
     *     {@link Recipient }
     *     
     */
    public void setRecipient(Recipient value) {
        this.recipient = value;
    }

    public String getInvoiceType() {
        return invoiceType;
    }

    public void setInvoiceType(String invoiceType) {
        this.invoiceType = invoiceType;
    }

    public String getTitleType() {
        return titleType;
    }

    public void setTitleType(String titleType) {
        this.titleType = titleType;
    }

    public String getItin() {
        return itin;
    }

    public void setItin(String itin) {
        this.itin = itin;
    }

    public Boolean getNeedRelationOrder() {
        return isNeedRelationOrder;
    }

    public void setNeedRelationOrder(Boolean needRelationOrder) {
        isNeedRelationOrder = needRelationOrder;
    }
}
