//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.09 at 10:10:23 AM CST 
//


package com.elong.nbopen.api.model.elong;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement; 
import java.util.List; 
import com.alibaba.fastjson.annotation.JSONField;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import java.util.Date;


/**
 * <p>Java class for OrderListCondition complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OrderListCondition">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CreationTimeFrom" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="CreationTimeTo" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="HotelId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RoomTypeId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RatePlanId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="ArrivalDateFrom" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="ArrivalDateTo" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="DepartureDateFrom" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="DepartureDateTo" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="Mobile" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CustomerName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PageIndex" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="MaxUpdateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="MinUpdateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="PageSize" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OrderListCondition", propOrder = {
    "creationTimeFrom",
    "creationTimeTo",
    "hotelId",
    "roomTypeId",
    "ratePlanId",
    "arrivalDateFrom",
    "arrivalDateTo",
    "departureDateFrom",
    "departureDateTo",
    "mobile",
    "customerName",
    "status",
    "pageIndex",
    "maxUpdateTime",
    "minUpdateTime",
    "pageSize"
})
public class OrderListCondition {

    @JSONField(name = "CreationTimeFrom")
    @XmlSchemaType(name = "dateTime")
    protected Date creationTimeFrom;
    @JSONField(name = "CreationTimeTo")
    @XmlSchemaType(name = "dateTime")
    protected Date creationTimeTo;
    @JSONField(name = "HotelId")
    protected String hotelId;
    @JSONField(name = "RoomTypeId")
    protected String roomTypeId;
    @JSONField(name = "RatePlanId")
    protected int ratePlanId;
    @JSONField(name = "ArrivalDateFrom")
    @XmlSchemaType(name = "dateTime")
    protected Date arrivalDateFrom;
    @JSONField(name = "ArrivalDateTo")
    @XmlSchemaType(name = "dateTime")
    protected Date arrivalDateTo;
    @JSONField(name = "DepartureDateFrom")
    @XmlSchemaType(name = "dateTime")
    protected Date departureDateFrom;
    @JSONField(name = "DepartureDateTo")
    @XmlSchemaType(name = "dateTime")
    protected Date departureDateTo;
    @JSONField(name = "Mobile")
    protected String mobile;
    @JSONField(name = "CustomerName")
    protected String customerName;
    @JSONField(name = "Status")
    protected String status;
    @JSONField(name = "PageIndex")
    protected int pageIndex;
    @JSONField(name = "MaxUpdateTime")
    @XmlSchemaType(name = "dateTime")
    protected Date maxUpdateTime;
    @JSONField(name = "MinUpdateTime")
    @XmlSchemaType(name = "dateTime")
    protected Date minUpdateTime;
    @JSONField(name = "PageSize")
    protected Integer pageSize;

    /**
     * Gets the value of the creationTimeFrom property.
     * 
     * @return
     *     possible object is
     *     {@link Date }
     *     
     */
    public Date getCreationTimeFrom() {
        return creationTimeFrom;
    }

    /**
     * Sets the value of the creationTimeFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link Date }
     *     
     */
    public void setCreationTimeFrom(Date value) {
        this.creationTimeFrom = value;
    }

    /**
     * Gets the value of the creationTimeTo property.
     * 
     * @return
     *     possible object is
     *     {@link Date }
     *     
     */
    public Date getCreationTimeTo() {
        return creationTimeTo;
    }

    /**
     * Sets the value of the creationTimeTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Date }
     *     
     */
    public void setCreationTimeTo(Date value) {
        this.creationTimeTo = value;
    }

    /**
     * Gets the value of the hotelId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHotelId() {
        return hotelId;
    }

    /**
     * Sets the value of the hotelId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHotelId(String value) {
        this.hotelId = value;
    }

    /**
     * Gets the value of the roomTypeId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRoomTypeId() {
        return roomTypeId;
    }

    /**
     * Sets the value of the roomTypeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRoomTypeId(String value) {
        this.roomTypeId = value;
    }

    /**
     * Gets the value of the ratePlanId property.
     * 
     */
    public int getRatePlanId() {
        return ratePlanId;
    }

    /**
     * Sets the value of the ratePlanId property.
     * 
     */
    public void setRatePlanId(int value) {
        this.ratePlanId = value;
    }

    /**
     * Gets the value of the arrivalDateFrom property.
     * 
     * @return
     *     possible object is
     *     {@link Date }
     *     
     */
    public Date getArrivalDateFrom() {
        return arrivalDateFrom;
    }

    /**
     * Sets the value of the arrivalDateFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link Date }
     *     
     */
    public void setArrivalDateFrom(Date value) {
        this.arrivalDateFrom = value;
    }

    /**
     * Gets the value of the arrivalDateTo property.
     * 
     * @return
     *     possible object is
     *     {@link Date }
     *     
     */
    public Date getArrivalDateTo() {
        return arrivalDateTo;
    }

    /**
     * Sets the value of the arrivalDateTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Date }
     *     
     */
    public void setArrivalDateTo(Date value) {
        this.arrivalDateTo = value;
    }

    /**
     * Gets the value of the departureDateFrom property.
     * 
     * @return
     *     possible object is
     *     {@link Date }
     *     
     */
    public Date getDepartureDateFrom() {
        return departureDateFrom;
    }

    /**
     * Sets the value of the departureDateFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link Date }
     *     
     */
    public void setDepartureDateFrom(Date value) {
        this.departureDateFrom = value;
    }

    /**
     * Gets the value of the departureDateTo property.
     * 
     * @return
     *     possible object is
     *     {@link Date }
     *     
     */
    public Date getDepartureDateTo() {
        return departureDateTo;
    }

    /**
     * Sets the value of the departureDateTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Date }
     *     
     */
    public void setDepartureDateTo(Date value) {
        this.departureDateTo = value;
    }

    /**
     * Gets the value of the mobile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * Sets the value of the mobile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMobile(String value) {
        this.mobile = value;
    }

    /**
     * Gets the value of the customerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerName() {
        return customerName;
    }

    /**
     * Sets the value of the customerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerName(String value) {
        this.customerName = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the pageIndex property.
     * 
     */
    public int getPageIndex() {
        return pageIndex;
    }

    /**
     * Sets the value of the pageIndex property.
     * 
     */
    public void setPageIndex(int value) {
        this.pageIndex = value;
    }

    /**
     * Gets the value of the maxUpdateTime property.
     * 
     * @return
     *     possible object is
     *     {@link Date }
     *     
     */
    public Date getMaxUpdateTime() {
        return maxUpdateTime;
    }

    /**
     * Sets the value of the maxUpdateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Date }
     *     
     */
    public void setMaxUpdateTime(Date value) {
        this.maxUpdateTime = value;
    }

    /**
     * Gets the value of the minUpdateTime property.
     * 
     * @return
     *     possible object is
     *     {@link Date }
     *     
     */
    public Date getMinUpdateTime() {
        return minUpdateTime;
    }

    /**
     * Sets the value of the minUpdateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Date }
     *     
     */
    public void setMinUpdateTime(Date value) {
        this.minUpdateTime = value;
    }

    /**
     * Gets the value of the pageSize property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPageSize() {
        return pageSize;
    }

    /**
     * Sets the value of the pageSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPageSize(Integer value) {
        this.pageSize = value;
    }

}
